services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: factory_user
      POSTGRES_PASSWORD: factory_pass
      POSTGRES_DB: factory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  simulator:
    build:
      context: .
      dockerfile: services/data_simulator/Dockerfile
    container_name: simulator
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  airflow:
    build:
      context: ./services/airflow
      dockerfile: Dockerfile
    container_name: airflow
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY="7AZPyRuhG3C6MN5ve-NeZ8zTSq1B75sUmBfpfbYAI94="
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://factory_user:factory_pass@postgres:5432/factory_db
    volumes:
      - ./services/airflow/dags:/opt/airflow/dags
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: standalone

  fastapi_app:
    build:
      context: ./services/fastapi_app
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - postgres
    ports:
      - "8000:8000"


volumes:
  postgres_data:





