services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: factory_user
      POSTGRES_PASSWORD: factory_pass
      POSTGRES_DB: factory_db
    ports:
      - "5432:5432"

  simulator:
    build:
      context: .
      dockerfile: services/data_simulator/Dockerfile
    container_name: simulator
    depends_on:
      - kafka
    # We'll override the default KAFKA_BOOTSTRAP_SERVERS variable
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    # If we want it always running, do nothing else. 
    # If we want it to run once and exit, we could do other settings...

